# Generated by Django 3.0.2 on 2020-01-26 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chord_progressions', '0002_auto_20200125_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordprogression',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
